### ISSUE TITLE
Pull Requests - here or on Unity's repository?

### ISSUE THREAD

**Issue by soraryu** [Whinarn/UnityMeshSimplifier#18]
Seeing that you're both active in this one and the Unity fork, I'm curious as to
a) which one I should be using in my project
b) where to fork from for pull requests with fixes/changes.

**Comment by Whinarn** [comment]
The Unity fork is a bit behind this one, so you would have access to the latest code here. I'm not sure if Unity will actually accept pull requests in their fork. It's all up to you which one you want to use. As I said though, this repository has the latest features and bug fixes. I'm only active here though. I'm not connected to Unity in any way and don't have access to their fork.

I don't actively develop on this plugin anymore, but if you have fixes and proposed changes, feel free to fork from this repository and open up pull requests.

**Comment by amirebrahimi** [comment]
I'll reinforce that any PRs should go to this repo. We fork public repositories that we make use of in Unity projects simply as a company policy.

As I see updates from this repo, I try to update the fork used by AutoLOD. You can always drop in the latest from this if you wish though.

Big thanks to @Whinarn for providing this library.

**Comment by soraryu** [comment]
Thanks for the clarification!
