### ISSUE TITLE
UnityMeshSimplifier mentioned recently...

### ISSUE THREAD

**Issue by amirebrahimi** [Whinarn/UnityMeshSimplifier#40]
This isn't a feature request, but figured I'd mention it in case you missed it:
https://www.gamasutra.com/blogs/RubenTorresBonet/20200915/370181/Simplify_Your_Life_With_Mesh_Simplifier.php

**Comment by Whinarn** [comment]
That's cool!
Thanks for making me aware, @amirebrahimi !
