### ISSUE TITLE
Last LODs Generated Are Not Saved

### ISSUE THREAD

**Issue by NateDawgg** [Whinarn/UnityMeshSimplifier#42]
Description:
The LODs that are generated for the last object are not saved. This occurs when following the steps below.

1. Extract and import the "Silver_and_White_Azerillo_Sporty_Hatchbacks.unitypackage" into Unity 2019.3.9f1
[Silver_and_White_Azerillo_Sporty_Hatchbacks.zip](https://github.com/Whinarn/UnityMeshSimplifier/files/5337230/Silver_and_White_Azerillo_Sporty_Hatchbacks.zip)
2. Double-click the "Assets/Azerilo/Car Model No.1201 Asset/Prefab/Sporty_Hatchback_silver.prefab" to open it.
3. Select the "Sporty_Hatchback_silver" node in the prefab hierarchy.
4. In the inspector menu, click "Add Component" and Select the LOD Generator Helper.
5. Enter the following settings, then right-click the LOD Generator Helper Component and select "Copy Component", then click the "Generate LODs" button.
![image](https://user-images.githubusercontent.com/18349886/95266246-cc90dc80-0800-11eb-8c36-80f290ac9778.png)
6. Next, double-click the "Assets/Azerilo/Car Model No.1201 Asset/Prefab/Sporty_Hatchback_white.prefab" to open it.
7. Select the "Sporty_Hatchback_white" node in the prefab hierarchy.
8. In the inspector menu, click "Add Component" and Select the LOD Generator Helper.
9. Right-click the LOD Generator Helper Component and select "Paste Component Values".
10. Click the Generate LODs button.
11. Double-click the "Assets/Azerilo/Car Model No.1201 Asset/Prefab/Sporty_Hatchback_silver.prefab" to re-open it.
12. Then, double-click the "Assets/Azerilo/Car Model No.1201 Asset/Prefab/Sporty_Hatchback_white.prefab" to re-open it.
13. The LODs that were generated in Step 10 were not saved and the "Generate LODs" button must be pressed again to re-generate LODs.

Expectation was that the generated LODs would still be there once I went away from the prefab and came back.

Thanks,
Nathan

**Comment by Whinarn** [comment]
Hi @NateDawgg,

Thanks for reporting this bug. I just wanted to let you know that I have read it, but don't currently have time to test it out myself right now. I'll hopefully get back to you within a few days.

**Comment by NateDawgg** [comment]
Hi @Whinarn 

OK, thanks so much!

**Comment by Whinarn** [comment]
Great reproduction steps, that really helps.
I have confirmed the bug, and believe this to related to marking things as dirty, so Unity isn't properly recognizing that things have changed. I'll see what I can do and get back to you when I have a fix!

**Comment by Whinarn** [comment]
@NateDawgg
I have just released [v2.3.5](https://github.com/Whinarn/UnityMeshSimplifier/releases/tag/v2.3.5) that should fix the bug that you experienced. The problem was as I expected, and was quite easy to resolve.

I was unable to reproduce the issue after this fix. Please confirm if the problem has been resolved for you as well.

**Comment by NateDawgg** [comment]
@Whinarn 
Thanks so much for the fix! I should be able to test later in the week and report back.

Cheers,
Nathan

**Comment by Whinarn** [comment]
@NateDawgg did you get a chance to confirm the fix yet?

**Comment by Whinarn** [comment]
I'll assume this to be fixed since there has been no response. If it's not, feel free to re-open again.
