### ISSUE TITLE
burst / jobs ?

### ISSUE THREAD

**Issue by klauskobald** [Whinarn/UnityMeshSimplifier#53]
there is this entry in the package json:
"com.unity.burst": "1.0.4"

... but I cannot find any burst related code. Is there intentions to use the job system?
That would be a big gain.

**Comment by Whinarn** [comment]
That might be a mistake. A year back or more I was looking into using Burst for this but aborted, so perhaps this was commited by mistake. Burst should not be necessary for the package today.

It would definitely be a big gain. Especially for runtime simplifications.

The previous issue is here: #14

**Comment by klauskobald** [comment]
ok. 
I will first try to burst my mesh creation code. If that works I will maybe look into the optimizer.

**Comment by klauskobald** [comment]
I found that the optimize method is thread save. So, I am currently using multiple threads to speed things up. Burst will have to wait.
