### ISSUE TITLE
Unable to install through Package Manager

### ISSUE THREAD

**Issue by TakUser** [Whinarn/UnityMeshSimplifier#57]
For some reason, the extension/add-on for Unity won't install.  I've tried the steps listed here: https://github.com/Whinarn/UnityMeshSimplifier/wiki/Installing-through-package-manager
I've also installed Git which I didn't have installed prior to the issue popping up.  I'm too scared that I might screw something up in the process of setting up the addon.

I get this error message upon attempting to install via Git link:
```
[Package Manager Window] Error adding package: https://github.com/Whinarn/UnityMeshSimplifier.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```
and

```
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/Whinarn/UnityMeshSimplifier.git]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**Environment (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Unity Version: 2020.3.26f1

**Additional context**
I already have both Git and a code editor installed.

**Comment by Whinarn** [comment]
Hi @TakUser ,
Sorry for a stupid question, but are you sure that Git is included in your `PATH` environment variable in Windows?
There's a long thread in the Unity forums regarding this problem that could help: https://forum.unity.com/threads/no-git-executable-was-found-please-install-git-on-your-system-and-restart-unity.730511/

**Comment by TakUser** [comment]
> Hi @TakUser , Sorry for a stupid question, but are you sure that Git is included in your `PATH` environment variable in Windows? There's a long thread in the Unity forums regarding this problem that could help: https://forum.unity.com/threads/no-git-executable-was-found-please-install-git-on-your-system-and-restart-unity.730511/

Not stupid at all!  This seemed to fix the issue of it not installing.  Many thanks for the link!
