### ISSUE TITLE
Wrong behavior on combined mesh

### ISSUE THREAD

**Issue by Azaberym** [Whinarn/UnityMeshSimplifier#61]
After generating a level, I'd like to get rid of unnecessary vertices by combining different meshs then using the mesh simplifier.

In this exemple, I'm starting with a grid of 900 square plane merged in one mesh using Mesh.CombineMeshes (3600 Vertices 1800 Triangles):
![image](https://user-images.githubusercontent.com/28675314/161831560-967a6cae-071e-49c2-a489-f8a998e329ca.png)

At this point, i'm using SimplifyMesh with the PreserveBorderEdges option to try to get a simplified square.
Here's what result (540 Vertices, 180 triangles):
![image](https://user-images.githubusercontent.com/28675314/161832302-3ef02122-6d83-4942-a8e7-f91032a5d603.png)

While it is totally possible that there is something that I don't get about the way the API works, this result doesn't feel right.

**Comment by Whinarn** [comment]
Hi @Azaberym ,
Sorry for the late reply. It has been a busy few days lately.

I believe this is related to an issue that has been coming up a few times related to planes and boxes tend to have clear visual defects after simplification. You can read more about this in the latest issue about this where I explained it in a bit more detail: https://github.com/Whinarn/UnityMeshSimplifier/issues/59

Unfortunately I'm not the author of the original algorithm, and quite honestly a lot of it is way about my expertise. I'd recommend this simplification for things like characters, animals, or certain environmental objects. It sucks with boxes and planes. And I have currently no plan to deal with that. I just simply don't have time nor the interest at the time. But I do welcome PRs if anyone is up for the challenge.

But as I said to the other person, if you find that the original algorithm works better in these scenarios, and you believe it to be a bug with my code, then please let me know!
But I'm closing this for now.
