### ISSUE TITLE
Getting the package from the packagemanager through the .git link is broken

### ISSUE THREAD

**Issue by Rackneh** [Whinarn/UnityMeshSimplifier#64]
Is it under construction?

**Comment by PabloMonfort** [comment]
its true, i have try the link and it dosnt work 
![image](https://github.com/Whinarn/UnityMeshSimplifier/assets/30636592/8bd52d01-83a5-4aaf-b3cf-1a010a22ab92)

**Comment by PabloMonfort** [comment]
btw i have figure out what i want and works perfectly! thank you m8! this is awesome :) 

![image](https://github.com/Whinarn/UnityMeshSimplifier/assets/30636592/cca61a27-2771-4658-bc9e-9c802debecb0)

i end up importing this runtime folder manually after download the whole zip and extract it . but worked fine in that way , thanks.

**Comment by Whinarn** [comment]
@PabloMonfort Aha, well if you read the error message that you provided in your screenshot it states that you do not have Git installed on your system.

If you do have it installed, make sure that it's reachable in the PATH environment variable.

If you do not have it installed or is unsure, please see requirements here: https://docs.unity3d.com/Manual/upm-ui-giturl.html
You will also find some troubleshooting there.
I'll make sure to mention this on the wiki page with instructions as well.

@Rackneh Please verify if you had the same problem. It's likely.

**Comment by PabloMonfort** [comment]
![image](https://github.com/Whinarn/UnityMeshSimplifier/assets/30636592/26d89ec1-1b42-465a-bffc-43bd5a3bdd32)
It works after install git and github and restart my pc. i used the via package manager and work, thanks and good work.
