### ISSUE TITLE
Mesh with vertex colors issue

### ISSUE THREAD

**Issue by Nostromo90** [Whinarn/UnityMeshSimplifier#7]
Hi,

i have another request (it's more enhancement than bug).

To maximize perfromances in VR I use special shader and vertex color of a mesh.
but when decimation is performed on a mesh with submeshes and several colors then you remove some vertices (maybe ducplicate) but without verifying the color of vertice

Here is the result.

![decimated](https://user-images.githubusercontent.com/39308345/40872953-aff39ccc-6657-11e8-8514-1a8958784335.PNG)
![notdecimated](https://user-images.githubusercontent.com/39308345/40872954-b0c8729e-6657-11e8-99d9-7a4d423d1743.PNG)

Could you do something? without impacting too much the performances of decimation?

TIA.

**Comment by Whinarn** [comment]
This might actually be a bug however. There should be more than one vertex sharing the same position around those yellow things, right? Because in that scenario where the vertices are sharing the same position but are not actually connected through triangles, then they shouldn't ever merge. With the smart linking feature they would be treated as one vertex, but the attributes should remain unique for both of them. But seeing this, it looks like vertices with the yellow color are being merged with vertices with the red color. Or that the vertex attributes are incorrectly used during the vertex merge process.

I will try to look into it from my side.
Are the red and yellow parts different sub-meshes?
Are they connected through triangles somewhere? Or are they separate islands so to speak?

**Comment by Nostromo90** [comment]
Hi, 

Yes it's 2 submeshes (1 red and 1 yellow)
For the other questions I don't know, so I provide you the mesh it will be easier (this one is public)

[quad.zip](https://github.com/Whinarn/UnityMeshSimplifier/files/2065124/quad.zip)

**Comment by Whinarn** [comment]
I think that I just figured out the problem just after posting this. I deal with UV-seams and UV-foldovers (when the UVs are the same on both sides), but in theory I should deal with attributes like color as well. Let me think about how to solve this. I will get back to you tomorrow, or next week once I get more time.

And thanks for the sample!

**Comment by Whinarn** [comment]
I looked into the mesh that you provided and I can see that the yellow and red parts are actually connected. See my screenshot below where I zoomed in and you can also clearly see the blending from the yellow/orange to red. I'm not sure that this can be easily solved actually. Especially not in a way that won't drain performance. But if you have any ideas, I would be open to them.

The problem I mentioned above is still real however and I will work on resolving that.

![image](https://user-images.githubusercontent.com/2932594/40878345-b0968b08-66ca-11e8-937e-bb92aede6510.png)

**Comment by Nostromo90** [comment]
Hi, 

First, I tested your new code enhanced. Performances are amazing Test performed
CAD file with 700 Meshes (about 30M of tris)
      - Former version: 30 minutes to read files, Parse and decimate 1 time for collider
      - New version: 4 minutes ot read files, Parse and decimate 2 times (MeshFilter and Meshcollider)
So congratulation for this code enhancement.

ABout my problem, I will have to check as it's really 2 SubMesh which are not shared same vertices (at least in the source)

As you can see in the screen of CAD source. Vertices and Triangles for Red and Yellow are not the same.
So I will look deeper in my code to understand why it seems to be merged (Unity enhancement of meshes? or my fault)

![redpart](https://user-images.githubusercontent.com/39308345/41090081-eb70eadc-6a32-11e8-830c-0055e3f566b1.PNG)
![yellowpart](https://user-images.githubusercontent.com/39308345/41090086-ee872de4-6a32-11e8-9867-1601c54616a4.PNG)

**Comment by Whinarn** [comment]
Great to see such huge improvements for you!

Could you verify the import settings in Unity for this model? Could it be "Optimize Mesh" that does this?

**Comment by Nostromo90** [comment]
Hi

Yes I Will check it deeper but you are probably right...
So in this case it will be difficult to fix it...

If I confirm on my side I will close the ticket

**Comment by Nostromo90** [comment]
Hi I confirm that same triangles contains 2 colors. 
Thanks for support
